"""
Centralized logging configuration for MassGen using loguru.

This module provides a unified logging system for all MassGen components,
with special focus on debugging orchestrator and agent backend activities.

Color Scheme for Debug Logging:
- Magenta: Orchestrator activities (🎯)
- Blue: Messages sent from orchestrator to agents (📤)
- Green: Messages received from agents (📥)
- Yellow: Backend activities (⚙️)
- Cyan: General agent activities (📨)
- Light-black: Tool calls (🔧)
- Red: Coordination steps (🔄)

Log File Structure:
- massgen.log: Main log with [SLOW] [ERROR] markers for easy grep
- events.jsonl: Structured events for TUI reconstruction and debugging
- metrics_summary.json: Detailed metrics (generated by orchestrator)
"""

import contextvars
import inspect
import os
import subprocess
import sys
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any, Optional

import yaml
from loguru import logger

from massgen.utils.redact_secrets import redact_secrets
from massgen.utils.sanitize_console_text import sanitize_console_text_for_encoding

if TYPE_CHECKING:
    from .events import EventEmitter

# Try to import massgen for version info (optional)
try:
    import massgen
except ImportError:
    massgen = None

# Remove default logger to have full control
logger.remove()

# Global debug flag
_DEBUG_MODE = False

# Global log session directory and turn tracking
_LOG_SESSION_DIR = None
_LOG_BASE_SESSION_DIR = None  # Base session dir (without turn subdirectory)
_CURRENT_TURN = None
_CURRENT_ATTEMPT = None  # Current attempt number for restart tracking

# Console logging suppression (for Rich Live display compatibility)
_CONSOLE_HANDLER_ID = None
_CONSOLE_SUPPRESSED = False

# Streaming debug handler ID (for full StreamChunk logging)
# DEPRECATED: Use events.jsonl via EventEmitter instead
_STREAMING_DEBUG_HANDLER_ID = None

# File handler IDs for reconfiguration on attempt change
_MAIN_LOG_HANDLER_ID = None
_STREAMING_LOG_HANDLER_ID = None

# Global event emitter for structured event logging
_EVENT_EMITTER: Optional["EventEmitter"] = None
# Shared implicit session for legacy/CLI callers that do not explicitly
# propagate ContextVar state across callbacks/tasks.
_IMPLICIT_SESSION: Optional["LoggingSession"] = None


# ---------------------------------------------------------------------------
# Per-run LoggingSession + ContextVar (for concurrent in-process isolation)
# ---------------------------------------------------------------------------


@dataclass
class LoggingSession:
    """Holds all mutable logging state for a single MassGen run.

    Storing this in a ContextVar (``_current_session``) instead of module
    globals makes concurrent ``massgen.run()`` calls safe: each asyncio task
    carries its own session without interfering with siblings.
    """

    session_id: str
    log_base_session_dir: Path | None = field(default=None)
    log_session_dir: Path | None = field(default=None)
    current_turn: int | None = field(default=None)
    current_attempt: int | None = field(default=None)
    debug_mode: bool = field(default=False)
    console_handler_id: int | None = field(default=None)
    console_suppressed: bool = field(default=False)
    main_log_handler_id: int | None = field(default=None)
    streaming_log_handler_id: int | None = field(default=None)
    event_emitter: Optional["EventEmitter"] = field(default=None)

    @classmethod
    def create(cls) -> "LoggingSession":
        """Create a new session with a unique ID."""
        return cls(session_id=uuid.uuid4().hex[:12])

    def close(self) -> None:
        """Remove this session's loguru file handlers and close its event emitter.

        Only this session's own handler IDs are removed; other sessions'
        handlers remain unaffected.
        """
        for hid in (self.main_log_handler_id, self.streaming_log_handler_id):
            if hid is not None:
                try:
                    logger.remove(hid)
                except ValueError:
                    pass  # Already removed
        if self.event_emitter is not None:
            try:
                self.event_emitter.close()
            except Exception:
                pass


# Module-level ContextVar: each asyncio task / thread gets its own slot.
_current_session: contextvars.ContextVar[LoggingSession | None] = contextvars.ContextVar("massgen_logging_session", default=None)


def _get_bound_or_implicit_session() -> LoggingSession | None:
    """Return the bound ContextVar session, falling back to implicit session."""
    session = _current_session.get(None)
    if session is not None:
        return session
    return _IMPLICIT_SESSION


def get_current_session() -> LoggingSession | None:
    """Return the active session for this context, or implicit legacy session."""
    return _get_bound_or_implicit_session()


def set_current_session(session: LoggingSession) -> contextvars.Token:
    """Bind *session* to the current context and return a reset token.

    Use the returned token with ``_current_session.reset(token)`` in a
    ``finally`` block to restore the previous session when the run ends.
    """
    return _current_session.set(session)


def get_current_attempt() -> int | None:
    """Return the current attempt number from the active session (or global fallback)."""
    session = _get_bound_or_implicit_session()
    if session is not None:
        return session.current_attempt
    return _CURRENT_ATTEMPT


def is_debug_mode() -> bool:
    """Return whether debug mode is enabled for the active session (or global fallback)."""
    session = _get_bound_or_implicit_session()
    if session is not None:
        return session.debug_mode
    return _DEBUG_MODE


def _make_session_filter(session_id: str):
    """Return a loguru filter function that passes records for *session_id*.

    Records that have no ``session_id`` bound (i.e. from modules that still
    use plain ``logger.info(...)`` instead of ``session_logger()``) are also
    accepted so that orchestrator/agent logs are not silently dropped.  Only
    records explicitly bound to a *different* session are rejected.
    """

    def _filter(record: Any) -> bool:
        if record["extra"].get("category") == "streaming_debug":
            return False
        record_sid = record["extra"].get("session_id", "")
        # Accept: matching session, OR unbound (empty string — legacy callers)
        return record_sid == session_id or record_sid == ""

    return _filter


def session_logger():
    """Return a loguru logger bound to the current session's ID.

    When no session is active (e.g., legacy single-run CLI code), the
    unbound ``logger`` is returned as a fallback so all call sites work
    without modification.
    """
    session = _get_bound_or_implicit_session()
    if session is not None:
        return logger.bind(session_id=session.session_id)
    return logger


class _ConsoleSafeSink:
    """File-like sink wrapper that protects console writes on non-UTF-8 terminals."""

    def __init__(self, stream: Any) -> None:
        self._stream = stream

    def write(self, message: Any) -> None:
        text = sanitize_console_text_for_encoding(
            str(message),
            getattr(self._stream, "encoding", None),
        )
        self._stream.write(text)

    def flush(self) -> None:
        flush = getattr(self._stream, "flush", None)
        if callable(flush):
            flush()


def _get_log_base_dir() -> Path:
    """Get the base directory that stores timestamped log sessions.

    Returns:
        Path to the directory that will contain ``log_*`` session folders.
        Defaults to ``.massgen/massgen_logs`` and can be overridden via
        ``MASSGEN_LOG_BASE_DIR``.
    """
    override = os.getenv("MASSGEN_LOG_BASE_DIR")
    if override:
        return Path(override).expanduser()
    return Path(".massgen") / "massgen_logs"


def get_log_session_dir(turn: int | None = None) -> Path:
    """Get the current log session directory, including attempt subdirectory if set.

    Args:
        turn: Optional turn number for multi-turn conversations

    Returns:
        Path to the log directory (includes attempt subdirectory if _CURRENT_ATTEMPT is set)
    """
    session = _get_bound_or_implicit_session()
    if session is not None:
        return _get_log_session_dir_for(session, turn=turn)

    # --- Legacy global fallback (single-run CLI / backward compat) ---
    global _LOG_SESSION_DIR, _LOG_BASE_SESSION_DIR, _CURRENT_TURN, _CURRENT_ATTEMPT

    # Initialize base session dir once per session
    if _LOG_BASE_SESSION_DIR is None:
        log_base_dir = _get_log_base_dir()
        log_base_dir.mkdir(parents=True, exist_ok=True)

        # Create timestamped session directory (with microseconds to prevent collisions)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
        _LOG_BASE_SESSION_DIR = log_base_dir / f"log_{timestamp}"
        _LOG_BASE_SESSION_DIR.mkdir(parents=True, exist_ok=True)

    # If turn changed, update the directory
    if turn is not None and turn != _CURRENT_TURN:
        _CURRENT_TURN = turn
        _LOG_SESSION_DIR = None  # Force recreation

    if _LOG_SESSION_DIR is None:
        # Build directory structure based on turn and attempt
        # ALWAYS use turn subdirectories (minimum turn_1)
        turn_num = _CURRENT_TURN if _CURRENT_TURN and _CURRENT_TURN > 0 else 1
        base_dir = _LOG_BASE_SESSION_DIR / f"turn_{turn_num}"

        # ALWAYS use attempt subdirectories (minimum attempt_1) for consistency
        # This ensures status.json path is predictable from the start
        attempt_num = _CURRENT_ATTEMPT if _CURRENT_ATTEMPT and _CURRENT_ATTEMPT > 0 else 1
        _LOG_SESSION_DIR = base_dir / f"attempt_{attempt_num}"

        _LOG_SESSION_DIR.mkdir(parents=True, exist_ok=True)

    return _LOG_SESSION_DIR


def _get_log_session_dir_for(session: LoggingSession, turn: int | None = None) -> Path:
    """Compute (and cache) the log dir for *session*, handling turn/attempt."""
    # Initialize base session dir once
    if session.log_base_session_dir is None:
        log_base_dir = _get_log_base_dir()
        log_base_dir.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
        session.log_base_session_dir = log_base_dir / f"log_{timestamp}"
        session.log_base_session_dir.mkdir(parents=True, exist_ok=True)

    # Update turn if provided
    if turn is not None and turn != session.current_turn:
        session.current_turn = turn
        session.log_session_dir = None  # Force recreation

    if session.log_session_dir is None:
        turn_num = session.current_turn if session.current_turn and session.current_turn > 0 else 1
        base_dir = session.log_base_session_dir / f"turn_{turn_num}"
        attempt_num = session.current_attempt if session.current_attempt and session.current_attempt > 0 else 1
        session.log_session_dir = base_dir / f"attempt_{attempt_num}"
        session.log_session_dir.mkdir(parents=True, exist_ok=True)

    return session.log_session_dir


def set_log_turn(turn: int) -> None:
    """Set the current turn number for multi-turn conversations.

    This forces the log directory to be recreated with the new turn subdirectory.

    Args:
        turn: Turn number (1-indexed)
    """
    session = _get_bound_or_implicit_session()
    if session is not None:
        session.current_turn = turn
        session.log_session_dir = None  # Force recreation
        return

    global _LOG_SESSION_DIR, _CURRENT_TURN
    _CURRENT_TURN = turn
    _LOG_SESSION_DIR = None  # Force recreation with new turn subdirectory


def set_log_attempt(attempt: int) -> None:
    """Set the current attempt number for restart tracking.

    This forces the log directory to be recreated with the new attempt subdirectory,
    and reconfigures file handlers to write to the new directory.

    Args:
        attempt: Attempt number (1-indexed)
    """
    session = _get_bound_or_implicit_session()
    if session is not None:
        session.current_attempt = attempt
        session.log_session_dir = None  # Force recreation
        new_log_dir = get_log_session_dir()

        console_format = "<green>{time:HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>"

        if session.main_log_handler_id is not None:
            try:
                logger.remove(session.main_log_handler_id)
            except ValueError:
                pass
            log_file = new_log_dir / "massgen.log"
            session.main_log_handler_id = logger.add(
                str(log_file),
                format=console_format,
                level="INFO",
                rotation="10 MB",
                retention="3 days",
                compression="zip",
                enqueue=True,
                colorize=False,
                filter=_make_session_filter(session.session_id),
            )
            logger.bind(session_id=session.session_id).info(
                "Reconfigured main log for attempt {}: {}",
                attempt,
                log_file,
            )

        if session.event_emitter is not None:
            session.event_emitter.set_log_dir(new_log_dir)
            logger.bind(session_id=session.session_id).info(
                "Reconfigured events.jsonl for attempt {}: {}",
                attempt,
                new_log_dir / "events.jsonl",
            )

        if session.streaming_log_handler_id is not None:
            try:
                logger.remove(session.streaming_log_handler_id)
            except ValueError:
                pass
            session.streaming_log_handler_id = None
        return

    global _LOG_SESSION_DIR, _CURRENT_ATTEMPT
    global _MAIN_LOG_HANDLER_ID, _STREAMING_LOG_HANDLER_ID, _STREAMING_DEBUG_HANDLER_ID
    global _EVENT_EMITTER

    _CURRENT_ATTEMPT = attempt
    _LOG_SESSION_DIR = None  # Force recreation with new attempt subdirectory

    # Get the new log directory
    new_log_dir = get_log_session_dir()

    # Reconfigure file handlers to point to new attempt directory
    if _MAIN_LOG_HANDLER_ID is not None:
        try:
            logger.remove(_MAIN_LOG_HANDLER_ID)
        except ValueError:
            pass  # Handler already removed

        console_format = "<green>{time:HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>"
        log_file = new_log_dir / "massgen.log"
        _MAIN_LOG_HANDLER_ID = logger.add(
            str(log_file),
            format=console_format,
            level="INFO",
            rotation="10 MB",
            retention="3 days",
            compression="zip",
            enqueue=True,
            colorize=False,
            filter=lambda record: record["extra"].get("category") != "streaming_debug",
        )
        logger.info("Reconfigured main log for attempt {}: {}", attempt, log_file)

    # Reconfigure event emitter to point to new attempt directory
    if _EVENT_EMITTER is not None:
        _EVENT_EMITTER.set_log_dir(new_log_dir)
        logger.info("Reconfigured events.jsonl for attempt {}: {}", attempt, new_log_dir / "events.jsonl")

    # Legacy streaming_debug.log handler (kept for backwards compatibility but unused)
    if _STREAMING_LOG_HANDLER_ID is not None:
        try:
            logger.remove(_STREAMING_LOG_HANDLER_ID)
        except ValueError:
            pass  # Handler already removed
        _STREAMING_LOG_HANDLER_ID = None
        _STREAMING_DEBUG_HANDLER_ID = None


def reset_logging_session() -> None:
    """Reset logging session state to allow creating a new log directory.

    Call this before each massgen.run() to ensure a fresh log directory
    is created for each run.  If a session is active in the current context,
    closes it and clears the ContextVar slot; otherwise clears the legacy globals.
    """
    session = _current_session.get(None)
    global _IMPLICIT_SESSION
    if session is not None:
        session.close()
        _current_session.set(None)
        if _IMPLICIT_SESSION is session:
            _IMPLICIT_SESSION = None
    elif _IMPLICIT_SESSION is not None:
        _IMPLICIT_SESSION.close()
        _IMPLICIT_SESSION = None

    global _LOG_BASE_SESSION_DIR, _LOG_SESSION_DIR, _CURRENT_TURN, _CURRENT_ATTEMPT
    _LOG_BASE_SESSION_DIR = None
    _LOG_SESSION_DIR = None
    _CURRENT_TURN = None
    _CURRENT_ATTEMPT = None


def set_log_base_session_dir(log_dir: str) -> None:
    """Set the base log session directory to an existing directory.

    Used when continuing a session to reuse the original log directory
    instead of creating a new timestamped one.

    Args:
        log_dir: Path to existing log directory (e.g., "log_20251101_151837")
    """
    session = _get_bound_or_implicit_session()
    log_base_dir = _get_log_base_dir()
    resolved = log_base_dir / log_dir
    resolved.mkdir(parents=True, exist_ok=True)
    if session is not None:
        session.log_base_session_dir = resolved
        session.log_session_dir = None
        return

    global _LOG_BASE_SESSION_DIR, _LOG_SESSION_DIR
    _LOG_BASE_SESSION_DIR = resolved
    _LOG_SESSION_DIR = None  # Force recreation with new base


def set_log_base_session_dir_absolute(log_dir_path: Path) -> None:
    """Set the base log session directory to an existing absolute path.

    Used by subagent orchestrator to inherit the parent's log directory
    instead of creating a new timestamped session.

    Args:
        log_dir_path: Absolute path to existing log directory
    """
    session = _get_bound_or_implicit_session()
    log_dir_path.mkdir(parents=True, exist_ok=True)
    if session is not None:
        session.log_base_session_dir = log_dir_path
        session.log_session_dir = None
        return

    global _LOG_BASE_SESSION_DIR, _LOG_SESSION_DIR
    _LOG_BASE_SESSION_DIR = log_dir_path
    _LOG_BASE_SESSION_DIR.mkdir(parents=True, exist_ok=True)
    _LOG_SESSION_DIR = None  # Force recreation with new base


def get_log_session_dir_base() -> Path:
    """Get the turn-level directory without attempt subdirectory.

    Returns the current turn directory (e.g., .massgen/massgen_logs/log_XXX/turn_1/)
    for copying final results from attempts.

    Returns:
        Path to turn directory (turn_N/) without attempt_N subdirectory
    """
    session = _get_bound_or_implicit_session()
    if session is not None:
        if session.log_base_session_dir is None:
            get_log_session_dir()
        turn_num = session.current_turn if session.current_turn and session.current_turn > 0 else 1
        return session.log_base_session_dir / f"turn_{turn_num}"

    global _LOG_BASE_SESSION_DIR, _CURRENT_TURN

    # Ensure base session dir is initialized
    if _LOG_BASE_SESSION_DIR is None:
        get_log_session_dir()

    # Return turn directory (minimum turn_1)
    turn_num = _CURRENT_TURN if _CURRENT_TURN and _CURRENT_TURN > 0 else 1
    return _LOG_BASE_SESSION_DIR / f"turn_{turn_num}"


def get_log_session_root() -> Path:
    """Get the session root directory (log_YYYYMMDD_HHMMSS).

    Returns the base log session directory without any turn or attempt subdirectories.
    Useful for getting the log directory name to save in session registry.

    Returns:
        Path to session root (e.g., .massgen/massgen_logs/log_20251104_191641)
    """
    session = _get_bound_or_implicit_session()
    if session is not None:
        if session.log_base_session_dir is None:
            get_log_session_dir()
        return session.log_base_session_dir

    global _LOG_BASE_SESSION_DIR

    # Ensure base session dir is initialized
    if _LOG_BASE_SESSION_DIR is None:
        get_log_session_dir()

    return _LOG_BASE_SESSION_DIR


def save_execution_metadata(
    query: str,
    config_path: str | None = None,
    config_content: dict | None = None,
    cli_args: dict | None = None,
):
    """Save the query and config metadata to the log directory.

    This allows reconstructing what was executed in this session.

    Args:
        query: The user's query/prompt
        config_path: Path to the config file that was used (optional)
        config_content: The actual config dictionary (optional)
        cli_args: Command line arguments as dict (optional)
    """
    log_dir = get_log_session_dir()

    # Create a single metadata file with all execution info
    metadata = {
        "query": query,
        "timestamp": datetime.now().isoformat(),
    }

    if config_path:
        metadata["config_path"] = str(config_path)

    if config_content:
        metadata["config"] = config_content

    if cli_args:
        metadata["cli_args"] = cli_args

    # Try to get git information if in a git repository
    try:
        git_commit = subprocess.check_output(["git", "rev-parse", "HEAD"], stderr=subprocess.DEVNULL, text=True).strip()
        git_branch = subprocess.check_output(["git", "rev-parse", "--abbrev-ref", "HEAD"], stderr=subprocess.DEVNULL, text=True).strip()
        metadata["git"] = {"commit": git_commit, "branch": git_branch}
    except (subprocess.CalledProcessError, FileNotFoundError):
        # Not in a git repo or git not available
        pass

    # Add Python version and package version
    metadata["python_version"] = sys.version
    if massgen is not None:
        metadata["massgen_version"] = getattr(massgen, "__version__", "unknown")

    # Add working directory
    metadata["working_directory"] = str(Path.cwd())

    metadata_file = log_dir / "execution_metadata.yaml"
    try:
        with open(metadata_file, "w", encoding="utf-8") as f:
            yaml.dump(metadata, f, default_flow_style=False, sort_keys=False, allow_unicode=True)
        logger.info(f"Saved execution metadata to: {metadata_file}")
    except Exception as e:
        logger.warning(f"Failed to save execution metadata: {e}")


def setup_logging(
    debug: bool = False,
    log_file: str | None = None,
    turn: int | None = None,
    session: LoggingSession | None = None,
):
    """
    Configure MassGen logging system using loguru.

    Args:
        debug: Enable debug mode with verbose logging
        log_file: Optional path to log file for persistent logging
        turn: Optional turn number for multi-turn conversations
        session: Optional LoggingSession to configure. If None, uses the active
            ContextVar session or creates an implicit one for backward compat.
    """
    # Resolve or create session
    global _IMPLICIT_SESSION
    if session is None:
        session = _current_session.get(None)
    if session is None:
        # Legacy / backward-compat path: reuse one implicit session so callers
        # that enter fresh ContextVar contexts keep writing to the same run.
        if _IMPLICIT_SESSION is None:
            _IMPLICIT_SESSION = LoggingSession.create()
        session = _IMPLICIT_SESSION
        _current_session.set(session)

    session.debug_mode = debug
    session.console_suppressed = False

    # Also update legacy globals for backward compat during migration
    global _DEBUG_MODE, _CONSOLE_HANDLER_ID, _CONSOLE_SUPPRESSED
    _DEBUG_MODE = debug
    _CONSOLE_SUPPRESSED = False

    # Remove existing handlers.  On the very first call for this session no
    # session-owned handlers exist yet, but loguru's default stderr handler
    # (ID 0) is still present.  A full logger.remove() is safe here because
    # no other sessions' sinks exist yet either.  On subsequent calls we only
    # remove the handlers we own so concurrent sessions aren't disturbed.
    if session.console_handler_id is None and session.main_log_handler_id is None:
        # First call for this session: only remove the default stderr handler
        # (ID 0) if it still exists.  Do NOT call bare logger.remove() which
        # would strip handlers belonging to other concurrent sessions.
        try:
            logger.remove(0)
        except ValueError:
            pass  # Already removed by module-level logger.remove() at import time
    else:
        if session.console_handler_id is not None:
            try:
                logger.remove(session.console_handler_id)
                session.console_handler_id = None
            except ValueError:
                pass
        if session.main_log_handler_id is not None:
            try:
                logger.remove(session.main_log_handler_id)
                session.main_log_handler_id = None
            except ValueError:
                pass

    if debug:
        # Debug mode: verbose console output with full details
        def custom_format(record):
            # Color code the module name based on category
            name = record["extra"].get("name", "")
            if "orchestrator" in name:
                name_color = "magenta"
            elif "backend" in name:
                name_color = "yellow"
            elif "agent" in name:
                name_color = "cyan"
            elif "coordination" in name:
                name_color = "red"
            else:
                name_color = "white"

            # Format the name to be more readable
            formatted_name = name if name else "{name}"

            return (
                f"<green>{{time:HH:mm:ss.SSS}}</green> | <level>{{level: <8}}</level> | "
                f"<{name_color}>{formatted_name}</{name_color}>:<{name_color}>{{function}}</{name_color}>:"
                f"<{name_color}>{{line}}</{name_color}> - {{message}}\n{{exception}}"
            )

        console_hid = logger.add(
            _ConsoleSafeSink(sys.stderr),
            format=custom_format,
            level="DEBUG",
            colorize=True,
            backtrace=True,
            diagnose=True,
        )
        session.console_handler_id = console_hid
        _CONSOLE_HANDLER_ID = console_hid

        # Also log to file in debug mode
        if not log_file:
            log_session_dir = get_log_session_dir(turn=turn)
            log_file = log_session_dir / "massgen_debug.log"

        session.main_log_handler_id = logger.add(
            str(log_file),
            format=custom_format,
            level="DEBUG",
            rotation="100 MB",
            retention="1 week",
            compression="zip",
            backtrace=True,
            diagnose=True,
            enqueue=True,  # Thread-safe logging
            colorize=False,  # Keep color codes in file
            filter=_make_session_filter(session.session_id),
        )

        logger.bind(session_id=session.session_id).info(
            "Debug logging enabled - logging to console and file: {}",
            log_file,
        )
    else:
        # Normal mode: only important messages to console, but all INFO+ to file
        console_format = "<green>{time:HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>"

        console_hid = logger.add(
            _ConsoleSafeSink(sys.stderr),
            format=console_format,
            level="WARNING",  # Only show WARNING and above on console in non-debug mode
            colorize=True,
        )
        session.console_handler_id = console_hid
        _CONSOLE_HANDLER_ID = console_hid

        # Always create log file in non-debug mode to capture INFO messages
        if not log_file:
            log_session_dir = get_log_session_dir(turn=turn)
            log_file = log_session_dir / "massgen.log"

        # Use session-filtered sink so concurrent sessions don't bleed into each other
        global _MAIN_LOG_HANDLER_ID, _STREAMING_LOG_HANDLER_ID, _EVENT_EMITTER
        file_hid = logger.add(
            str(log_file),
            format=console_format,
            level="INFO",  # Capture INFO and above in file
            rotation="10 MB",
            retention="3 days",
            compression="zip",
            enqueue=True,
            colorize=False,  # Keep color codes in file
            filter=_make_session_filter(session.session_id),
        )
        session.main_log_handler_id = file_hid
        _MAIN_LOG_HANDLER_ID = file_hid  # backward compat

        # Initialize EventEmitter for structured event logging (supplements streaming_debug.log)
        from .events import EventEmitter, set_event_emitter

        # Preserve listeners from previous emitter (e.g., TUI event listener)
        # when re-creating for a new turn
        old_emitter = session.event_emitter
        old_listeners = old_emitter._listeners.copy() if old_emitter else []
        if old_emitter is not None:
            old_emitter.close()
        new_emitter = EventEmitter(log_session_dir)
        for listener in old_listeners:
            new_emitter.add_listener(listener)
        session.event_emitter = new_emitter

        # Also keep legacy global in sync for backward compat
        _EVENT_EMITTER = new_emitter
        set_event_emitter(new_emitter)

        logger.bind(session_id=session.session_id).info(
            "Logging enabled - logging INFO+ to file: {}",
            log_file,
        )
        logger.bind(session_id=session.session_id).info(
            "Events log: {}",
            log_session_dir / "events.jsonl",
        )


def integrate_logfire_with_loguru():
    """
    Integrate Logfire with loguru so that log messages are also sent to Logfire.

    This should be called after both setup_logging() and configure_observability()
    have been called. It uses Logfire's built-in loguru instrumentation.
    """
    try:
        from .structured_logging import is_observability_enabled

        if not is_observability_enabled():
            return

        import logfire

        # Logfire has built-in loguru integration
        logfire.instrument_loguru()
        logger.debug("Logfire integrated with loguru")
    except ImportError:
        pass  # Logfire not available
    except Exception as e:
        logger.debug(f"Could not integrate Logfire with loguru: {e}")


def suppress_console_logging():
    """
    Temporarily suppress console logging to prevent interference with Rich Live display.

    This removes the console handler while keeping file logging active.
    Call restore_console_logging() to re-enable console output.
    """
    global _CONSOLE_HANDLER_ID, _CONSOLE_SUPPRESSED

    if _CONSOLE_HANDLER_ID is not None and not _CONSOLE_SUPPRESSED:
        try:
            logger.remove(_CONSOLE_HANDLER_ID)
            _CONSOLE_SUPPRESSED = True
        except ValueError:
            # Handler already removed
            pass


def restore_console_logging():
    """
    Restore console logging after it was suppressed.

    Re-adds the console handler with the same settings that were used during setup.
    """
    global _CONSOLE_HANDLER_ID, _CONSOLE_SUPPRESSED, _DEBUG_MODE

    if not _CONSOLE_SUPPRESSED:
        return

    # Re-add console handler with same settings as setup_logging
    if _DEBUG_MODE:

        def custom_format(record):
            name = record["extra"].get("name", "")
            if "orchestrator" in name:
                name_color = "magenta"
            elif "backend" in name:
                name_color = "yellow"
            elif "agent" in name:
                name_color = "cyan"
            elif "coordination" in name:
                name_color = "red"
            else:
                name_color = "white"
            formatted_name = name if name else "{name}"
            return (
                f"<green>{{time:HH:mm:ss.SSS}}</green> | <level>{{level: <8}}</level> | "
                f"<{name_color}>{formatted_name}</{name_color}>:<{name_color}>{{function}}</{name_color}>:"
                f"<{name_color}>{{line}}</{name_color}> - {{message}}\n{{exception}}"
            )

        _CONSOLE_HANDLER_ID = logger.add(
            _ConsoleSafeSink(sys.stderr),
            format=custom_format,
            level="DEBUG",
            colorize=True,
            backtrace=True,
            diagnose=True,
        )
    else:
        console_format = "<green>{time:HH:mm:ss}</green> | <level>{level: <8}</level> | <level>{message}</level>"
        _CONSOLE_HANDLER_ID = logger.add(
            _ConsoleSafeSink(sys.stderr),
            format=console_format,
            level="WARNING",
            colorize=True,
        )

    _CONSOLE_SUPPRESSED = False


def get_logger(name: str):
    """
    Get a logger instance with the given name.

    Args:
        name: Logger name (typically __name__ of the module)

    Returns:
        Configured logger instance
    """
    return logger.bind(name=name)


def _get_caller_info():
    """
    Get the caller's line number and function name from the stack frame.

    Returns:
        Tuple of (function_name, line_number where the logging function was called)
    """
    frame = inspect.currentframe()
    # Stack frames:
    # - frame: _get_caller_info (this function)
    # - frame.f_back: log_orchestrator_agent_message or log_backend_agent_message
    # - frame.f_back.f_back: the actual caller (e.g., _stream_agent_execution)

    if frame and frame.f_back and frame.f_back.f_back:
        caller_frame = frame.f_back.f_back
        function_name = caller_frame.f_code.co_name
        # Get the line number where the logging function was called from within the caller
        line_number = caller_frame.f_lineno
        return function_name, line_number
    return "unknown", 0


def log_orchestrator_activity(orchestrator_id: str, activity: str, details: dict = None):
    """
    Log orchestrator activities for debugging.

    Args:
        orchestrator_id: ID of the orchestrator
        activity: Description of the activity
        details: Additional details as dictionary
    """
    # Get caller information
    func_name, line_num = _get_caller_info()
    log = logger.bind(name=f"orchestrator.{orchestrator_id}:{func_name}:{line_num}")
    if _DEBUG_MODE:
        # Use magenta color for orchestrator activities
        log.opt(colors=True).debug("<magenta>🎯 {}: {}</magenta>", activity, details or {})


def log_agent_message(agent_id: str, direction: str, message: dict, backend_name: str = None):
    """
    Log agent messages (sent/received) for debugging.

    Args:
        agent_id: ID of the agent
        direction: "SEND" or "RECV"
        message: Message content as dictionary
        backend_name: Optional name of the backend provider
    """
    # Build a descriptive name with both agent ID and backend
    if backend_name:
        log_name = f"{agent_id}.{backend_name}"
        log = logger.bind(name=log_name)
    else:
        log_name = agent_id
        log = logger.bind(name=log_name)

    if _DEBUG_MODE:
        if direction == "SEND":
            # Use blue color for sent messages
            log.opt(colors=True).debug(
                "<blue>📤 [{}] Sending message: {}</blue>",
                log_name,
                _format_message(message),
            )
        elif direction == "RECV":
            # Use green color for received messages
            log.opt(colors=True).debug(
                "<green>📥 [{}] Received message: {}</green>",
                log_name,
                _format_message(message),
            )
        else:
            log.opt(colors=True).debug(
                "<cyan>📨 [{}] {}: {}</cyan>",
                log_name,
                direction,
                _format_message(message),
            )


def log_orchestrator_agent_message(agent_id: str, direction: str, message: dict, backend_name: str = None):
    """
    Log orchestrator-to-agent messages for debugging.

    Args:
        agent_id: ID of the agent
        direction: "SEND" or "RECV"
        message: Message content as dictionary
        backend_name: Optional name of the backend provider
    """
    # Get caller information
    func_name, line_num = _get_caller_info()

    # Build a descriptive name with orchestrator prefix
    if backend_name:
        log_name = f"orchestrator→{agent_id}.{backend_name}:{func_name}:{line_num}"
        log = logger.bind(name=log_name)
    else:
        log_name = f"orchestrator→{agent_id}:{func_name}:{line_num}"
        log = logger.bind(name=log_name)

    if _DEBUG_MODE:
        if direction == "SEND":
            # Use magenta color for orchestrator sent messages
            log.opt(colors=True).debug(
                "<magenta>🎯📤 [{}] Orchestrator sending to agent: {}</magenta>",
                log_name,
                _format_message(message),
            )
        elif direction == "RECV":
            # Use magenta color for orchestrator received messages
            log.opt(colors=True).debug(
                "<magenta>🎯📥 [{}] Orchestrator received from agent: {}</magenta>",
                log_name,
                _format_message(message),
            )
        else:
            log.opt(colors=True).debug(
                "<magenta>🎯📨 [{}] {}: {}</magenta>",
                log_name,
                direction,
                _format_message(message),
            )


def log_backend_agent_message(agent_id: str, direction: str, message: dict, backend_name: str = None):
    """
    Log backend-to-LLM messages for debugging.

    Args:
        agent_id: ID of the agent
        direction: "SEND" or "RECV"
        message: Message content as dictionary
        backend_name: Optional name of the backend provider
    """
    # Get caller information
    func_name, line_num = _get_caller_info()

    # Build a descriptive name with backend prefix
    if backend_name:
        log_name = f"backend.{backend_name}→{agent_id}:{func_name}:{line_num}"
        log = logger.bind(name=log_name)
    else:
        log_name = f"backend→{agent_id}:{func_name}:{line_num}"
        log = logger.bind(name=log_name)

    if _DEBUG_MODE:
        if direction == "SEND":
            # Use yellow color for backend sent messages
            log.opt(colors=True).debug(
                "<yellow>⚙️📤 [{}] Backend sending to LLM: {}</yellow>",
                log_name,
                _format_message(message),
            )
        elif direction == "RECV":
            # Use yellow color for backend received messages
            log.opt(colors=True).debug(
                "<yellow>⚙️📥 [{}] Backend received from LLM: {}</yellow>",
                log_name,
                _format_message(message),
            )
        else:
            log.opt(colors=True).debug(
                "<yellow>⚙️📨 [{}] {}: {}</yellow>",
                log_name,
                direction,
                _format_message(message),
            )


def log_backend_activity(backend_name: str, activity: str, details: dict = None, agent_id: str = None):
    """
    Log backend activities for debugging.

    Args:
        backend_name: Name of the backend (e.g., "openai", "claude")
        activity: Description of the activity
        details: Additional details as dictionary
        agent_id: Optional ID of the agent using this backend
    """
    # Get caller information
    func_name, line_num = _get_caller_info()

    # Build a descriptive name with both agent ID and backend
    if agent_id:
        log_name = f"{agent_id}.{backend_name}"
        log = logger.bind(name=f"{log_name}:{func_name}:{line_num}")
    else:
        log_name = backend_name
        log = logger.bind(name=f"backend.{backend_name}:{func_name}:{line_num}")

    if _DEBUG_MODE:
        # Use yellow color for backend activities
        log.opt(colors=True).debug("<yellow>⚙️ [{}] {}: {}</yellow>", log_name, activity, details or {})


def log_mcp_activity(backend_name: str, message: str, details: dict = None, agent_id: str = None):
    """
    Log MCP (Model Context Protocol) activities at INFO level.

    Args:
        backend_name: Name of the backend (e.g., "claude", "openai")
        message: Description of the MCP activity
        details: Additional details as dictionary
        agent_id: Optional ID of the agent using this backend
    """
    func_name, line_num = _get_caller_info()

    if agent_id:
        log_name = f"{agent_id}.{backend_name}"
        log = logger.bind(name=f"{log_name}:{func_name}:{line_num}")
    else:
        log_name = backend_name
        log = logger.bind(name=f"backend.{backend_name}:{func_name}:{line_num}")

    log.info("MCP: {} - {}", message, details or {})


def log_tool_call(
    agent_id: str,
    tool_name: str,
    arguments: dict,
    result: Any = None,
    backend_name: str = None,
):
    """
    Log tool calls made by agents.

    Args:
        agent_id: ID of the agent making the tool call
        tool_name: Name of the tool being called
        arguments: Arguments passed to the tool
        result: Result returned by the tool (optional)
        backend_name: Optional name of the backend provider
    """
    # Build a descriptive name with both agent ID and backend
    if backend_name:
        log_name = f"{agent_id}.{backend_name}"
        log = logger.bind(name=f"{log_name}.tools")
    else:
        log_name = agent_id
        log = logger.bind(name=f"{agent_id}.tools")

    if _DEBUG_MODE:
        if result is not None:
            # Use light gray color for tool calls
            log.opt(colors=True).debug(
                "<light-black>🔧 [{}] Tool '{}' called with args: {} -> Result: {}</light-black>",
                log_name,
                tool_name,
                arguments,
                result,
            )
        else:
            log.opt(colors=True).debug(
                "<light-black>🔧 [{}] Calling tool '{}' with args: {}</light-black>",
                log_name,
                tool_name,
                arguments,
            )


def log_coordination_step(step: str, details: dict = None):
    """
    Log coordination workflow steps.

    Args:
        step: Description of the coordination step
        details: Additional details as dictionary
    """
    log = logger.bind(name="coordination")
    if _DEBUG_MODE:
        # Use red color for coordination steps (distinctive from orchestrator)
        log.opt(colors=True).debug("<red>🔄 {}: {}</red>", step, details or {})


def log_streaming_debug(chunk: Any, agent_id: str | None = None):
    """
    Log StreamChunk for detailed debugging via loguru.

    Note: STREAM_CHUNK events are no longer written to events.jsonl.
    Structured events (TOOL_START, TOOL_COMPLETE, THINKING, TEXT, etc.)
    replace STREAM_CHUNK for TUI reconstruction.

    Args:
        chunk: The StreamChunk object to log
        agent_id: Optional agent ID to associate with the chunk
    """
    log = logger.bind(category="streaming_debug")
    log.debug(f"🔹 [chat] Yielding chunk: {chunk}")


def get_event_emitter() -> Optional["EventEmitter"]:
    """Get the global event emitter instance.

    Returns:
        The EventEmitter instance, or None if logging not initialized
    """
    return _EVENT_EMITTER


def log_stream_chunk(source: str, chunk_type: str, content: Any = None, agent_id: str = None):
    """
    Log stream chunks at INFO level (always logged to file).

    Includes [SLOW] and [ERROR] markers for easy grep.

    Args:
        source: Source of the stream chunk (e.g., "orchestrator", "backend.claude_code")
        chunk_type: Type of the chunk (e.g., "content", "tool_call", "error")
        content: Content of the chunk
        agent_id: Optional agent ID for context
    """
    # Get caller information from the actual caller (not this function)
    frame = inspect.currentframe()
    if frame and frame.f_back:
        caller_frame = frame.f_back
        function_name = caller_frame.f_code.co_name
        line_number = caller_frame.f_lineno
    else:
        function_name = "unknown"
        line_number = 0

    if agent_id:
        log_name = f"{source}.{agent_id}"
    else:
        log_name = source

    # Create a custom logger that will show the source name instead of module path
    log = logger.bind(name=f"{log_name}:{function_name}:{line_number}")
    redacted_content = redact_secrets(content)

    # Handle tool_result chunks with timing info - add [SLOW] marker for operations >5s
    if chunk_type == "tool_result" and isinstance(redacted_content, dict):
        exec_time = redacted_content.get("execution_time", 0)
        command = redacted_content.get("command", "")
        if exec_time > 5.0:
            command_preview = command[:50] + "..." if len(command) > 50 else command
            log.warning(f"[SLOW] {command_preview} took {exec_time:.1f}s")
            return

    # Handle error chunks with [ERROR] marker
    if chunk_type == "error" or (isinstance(redacted_content, dict) and redacted_content.get("is_error")):
        log.error(f"[ERROR] {source}: {redacted_content}")
        return

    # Normal logging for other chunks
    if redacted_content:
        log.info("Stream chunk [{}]: {}", chunk_type, redacted_content)
    else:
        log.info("Stream chunk [{}]", chunk_type)


def _format_message(message: dict) -> str:
    """
    Format message for logging without truncation.

    Args:
        message: Message dictionary

    Returns:
        Formatted message string
    """
    if not message:
        return "<empty>"

    # Format based on message type
    if "role" in message and "content" in message:
        content = message.get("content", "")
        if isinstance(content, str):
            # No truncation - show full content
            return f"[{message['role']}] {content}"
        else:
            return f"[{message['role']}] {str(content)}"

    # For other message types, just stringify without truncation
    msg_str = str(message)
    return msg_str


# Export main components
__all__ = [
    "logger",
    "setup_logging",
    "integrate_logfire_with_loguru",
    "suppress_console_logging",
    "restore_console_logging",
    "get_logger",
    "get_log_session_dir",
    "get_log_session_dir_base",
    "get_log_session_root",
    "set_log_turn",
    "set_log_attempt",
    "set_log_base_session_dir",
    "set_log_base_session_dir_absolute",
    "reset_logging_session",
    "save_execution_metadata",
    "log_orchestrator_activity",
    "log_agent_message",
    "log_orchestrator_agent_message",
    "log_backend_agent_message",
    "log_backend_activity",
    "log_mcp_activity",
    "log_tool_call",
    "log_coordination_step",
    "log_stream_chunk",
    "log_streaming_debug",
    "get_event_emitter",
]
