"""
Run MassGen with terminal recording and evaluate the frontend display.

This tool uses VHS (https://github.com/charmbracelet/vhs) to record MassGen terminal
sessions as videos, then analyzes them using the understand_video tool.
"""

import json
import os
import shutil
import subprocess
import tempfile
import time
from pathlib import Path

from massgen.tool._result import ExecutionResult, TextContent


def _validate_path_access(path: Path, allowed_paths: list[Path] | None = None) -> None:
    """
    Validate that a path is within allowed directories.

    Args:
        path: Path to validate
        allowed_paths: List of allowed base paths (optional)

    Raises:
        ValueError: If path is not within allowed directories
    """
    if not allowed_paths:
        return  # No restrictions

    for allowed_path in allowed_paths:
        try:
            path.relative_to(allowed_path)
            return  # Path is within this allowed directory
        except ValueError:
            continue

    raise ValueError(f"Path not in allowed directories: {path}")


def _check_vhs_installed() -> bool:
    """
    Check if VHS is installed and available.

    Returns:
        True if VHS is installed, False otherwise
    """
    try:
        result = subprocess.run(
            ["vhs", "--version"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        return result.returncode == 0
    except (subprocess.SubprocessError, FileNotFoundError):
        return False


def _create_vhs_tape(
    command: str,
    output_path: Path,
    output_format: str = "mp4",
    width: int = 1200,
    height: int = 800,
    timeout_seconds: int = 300,
) -> str:
    """
    Create a VHS tape file for recording the terminal session.

    Args:
        command: Command to run (e.g., "uv run massgen --config X 'Question'")
        output_path: Path where the video will be saved
        output_format: Output format (mp4, gif, or webm)
        width: Terminal width in pixels
        height: Terminal height in pixels
        timeout_seconds: Maximum time to wait for command completion

    Returns:
        VHS tape content as string
    """
    # VHS tape format: https://github.com/charmbracelet/vhs
    # Note: VHS supports backticks for Type command to handle nested quotes
    tape_content = f"""# VHS tape for MassGen terminal recording
# Auto-generated by run_massgen_with_recording tool

# Output configuration
Output "{output_path}"

# Set terminal size
Set Width {width}
Set Height {height}

# Set font size (smaller for more content)
Set FontSize 15

# Set terminal theme (optional, can be customized)
Set Theme "Dracula"

# Set shell to bash with no config files
Set Shell bash

# Set wait timeout (max time to wait for prompt)
Set WaitTimeout {timeout_seconds}s

# Typing speed (faster for automation)
Set TypingSpeed 50ms

# Hide the setup commands from the recording
Hide

# Set a simple prompt to avoid shell config issues
Type `export PS1='$ '`
Enter
Sleep 0.2s

# Clear the screen for a clean recording
Type `clear`
Enter
Sleep 0.2s

# Type the MassGen command (with --skip-agent-selector flag)
Type `{command}`

# Show the recording from here
Show

# Execute the command
Enter

# Small initial delay to let command start
Sleep 1s

# Wait for shell prompt to return on the current line (command finished)
# This waits for $ to appear on a NEW line after command completes
# Max timeout is set by WaitTimeout above
Wait /\\$/

# Capture final frame after completion
Sleep 2s
"""

    return tape_content


async def run_massgen_with_recording(
    config_path: str,
    question: str,
    output_format: str = "mp4",
    timeout_seconds: int = 300,
    width: int = 1920,
    height: int = 1080,
    allowed_paths: list[str] | None = None,
    agent_cwd: str | None = None,
) -> ExecutionResult:
    """
    Run MassGen with terminal recording and save the video.

    This tool records a MassGen session using VHS (https://github.com/charmbracelet/vhs)
    and saves the video to the agent workspace. The agent can then use understand_video
    tool separately to analyze the recording as needed.

    Args:
        config_path: Path to MassGen config file (YAML)
                    - Relative path: Resolved relative to workspace
                    - Absolute path: Must be within allowed directories
        question: Question to pass to MassGen
        output_format: Video format - "mp4" (default), "gif", or "webm"
        timeout_seconds: Maximum time to wait for MassGen to complete (default: 300)
        width: Terminal width in pixels (default: 1200)
        height: Terminal height in pixels (default: 800)
        allowed_paths: List of allowed base paths for validation (optional)
        agent_cwd: Agent's current working directory (automatically injected, optional)

    Returns:
        ExecutionResult containing:
        - success: Whether operation succeeded
        - operation: "run_massgen_with_recording"
        - config_path: Path to the config file used
        - question: The question passed to MassGen
        - video_path: Path to the recorded video (saved in workspace)
        - video_format: Format of the video (mp4/gif/webm)
        - video_size_bytes: Size of the video file in bytes
        - recording_duration_seconds: How long the recording took
        - massgen_timeout_seconds: Max timeout that was set
        - terminal_dimensions: Dict with width and height
        - errors: Any errors encountered

    Examples:
        # Record a MassGen session
        result = run_massgen_with_recording(
            "massgen/configs/tools/todo/example_task_todo.yaml",
            "Create a simple HTML page about Bob Dylan"
        )
        → Records MassGen session and saves video to workspace

        # Then analyze with understand_video separately
        evaluation = understand_video(
            result["video_path"],
            "Evaluate the terminal display quality",
            num_frames=12
        )

        # Record as GIF for documentation
        run_massgen_with_recording(
            "my_config.yaml",
            "Solve the maze problem",
            output_format="gif"
        )
        → Records as GIF for easy embedding in docs

    Prerequisites:
        - VHS must be installed: https://github.com/charmbracelet/vhs
          Install: `brew install vhs` (macOS) or `go install github.com/charmbracelet/vhs@latest`

    Security:
        - Config file must exist and be readable
        - Video files saved to agent workspace

    Note:
        - This tool runs MassGen WITHOUT --automation flag to capture the rich terminal display
        - Uses --skip-agent-selector flag so MassGen exits cleanly after showing final answer
        - Uses VHS Wait command to end recording automatically when command finishes
        - timeout_seconds is maximum wait time; recording ends early if MassGen finishes sooner
        - Recording quality depends on terminal theme, font size, and VHS settings
        - Video is saved to workspace - use understand_video separately to analyze it
    """
    try:
        # Convert allowed_paths from strings to Path objects
        allowed_paths_list = [Path(p) for p in allowed_paths] if allowed_paths else None

        # Resolve base directory
        base_dir = Path(agent_cwd) if agent_cwd else Path.cwd()

        # Resolve config path
        if Path(config_path).is_absolute():
            cfg_path = Path(config_path).resolve()
        else:
            cfg_path = (base_dir / config_path).resolve()

        # Validate config path
        _validate_path_access(cfg_path, allowed_paths_list)

        if not cfg_path.exists():
            result = {
                "success": False,
                "operation": "run_massgen_with_recording",
                "error": f"Config file does not exist: {cfg_path}",
            }
            return ExecutionResult(
                output_blocks=[TextContent(data=json.dumps(result, indent=2))],
            )

        # Check if VHS is installed
        if not _check_vhs_installed():
            result = {
                "success": False,
                "operation": "run_massgen_with_recording",
                "error": "VHS is not installed. Please install it from https://github.com/charmbracelet/vhs\n" "Install: brew install vhs (macOS) or go install github.com/charmbracelet/vhs@latest",
            }
            return ExecutionResult(
                output_blocks=[TextContent(data=json.dumps(result, indent=2))],
            )

        # Validate output format
        valid_formats = ["mp4", "gif", "webm"]
        if output_format.lower() not in valid_formats:
            result = {
                "success": False,
                "operation": "run_massgen_with_recording",
                "error": f"Invalid output format: {output_format}. Must be one of: {', '.join(valid_formats)}",
            }
            return ExecutionResult(
                output_blocks=[TextContent(data=json.dumps(result, indent=2))],
            )

        # Create temporary directory for recording
        with tempfile.TemporaryDirectory(prefix="massgen_recording_") as temp_dir:
            temp_path = Path(temp_dir)

            # Define output paths
            video_filename = f"massgen_terminal.{output_format.lower()}"
            video_path = temp_path / video_filename
            tape_path = temp_path / "recording.tape"

            # Build MassGen command (WITHOUT --automation to capture rich terminal)
            # Use --skip-agent-selector to auto-quit after showing final answer
            # Escape quotes in the question
            escaped_question = question.replace('"', '\\"')
            massgen_command = f'uv run massgen --skip-agent-selector --config "{cfg_path}" "{escaped_question}"'

            # Create VHS tape file
            tape_content = _create_vhs_tape(
                command=massgen_command,
                output_path=video_path,
                output_format=output_format,
                width=width,
                height=height,
                timeout_seconds=timeout_seconds,
            )

            # Write tape file
            tape_path.write_text(tape_content)

            # Run VHS to record the session
            # VHS Wait command will automatically end when shell prompt returns
            try:
                vhs_start_time = time.time()
                vhs_result = subprocess.run(
                    ["vhs", str(tape_path)],
                    cwd=str(temp_path),
                    capture_output=True,
                    text=True,
                    timeout=timeout_seconds + 60,  # Extra buffer for VHS processing
                )
                vhs_duration = time.time() - vhs_start_time

                # Check if VHS succeeded
                if vhs_result.returncode != 0:
                    # Read the tape file for debugging
                    tape_debug = tape_path.read_text() if tape_path.exists() else "Tape file not found"
                    result = {
                        "success": False,
                        "operation": "run_massgen_with_recording",
                        "error": f"VHS recording failed with exit code {vhs_result.returncode}",
                        "vhs_stdout": vhs_result.stdout,
                        "vhs_stderr": vhs_result.stderr,
                        "tape_file": tape_debug,
                        "tape_path": str(tape_path),
                    }
                    return ExecutionResult(
                        output_blocks=[TextContent(data=json.dumps(result, indent=2))],
                    )

                # Check if video file was created
                if not video_path.exists():
                    result = {
                        "success": False,
                        "operation": "run_massgen_with_recording",
                        "error": "VHS completed but video file was not created",
                        "vhs_stdout": vhs_result.stdout,
                        "vhs_stderr": vhs_result.stderr,
                    }
                    return ExecutionResult(
                        output_blocks=[TextContent(data=json.dumps(result, indent=2))],
                    )

                # Copy video to workspace for reuse
                workspace_video_path = base_dir / video_filename
                shutil.copy2(video_path, workspace_video_path)

                # Compile final result (video is saved, agent can call understand_video separately)
                result = {
                    "success": True,
                    "operation": "run_massgen_with_recording",
                    "config_path": str(cfg_path),
                    "question": question,
                    "video_path": str(workspace_video_path),
                    "video_format": output_format,
                    "video_size_bytes": os.path.getsize(workspace_video_path),
                    "recording_duration_seconds": round(vhs_duration, 2),
                    "massgen_timeout_seconds": timeout_seconds,
                    "terminal_dimensions": {"width": width, "height": height},
                }

                return ExecutionResult(
                    output_blocks=[TextContent(data=json.dumps(result, indent=2))],
                )

            except subprocess.TimeoutExpired:
                result = {
                    "success": False,
                    "operation": "run_massgen_with_recording",
                    "error": f"VHS recording timed out after {timeout_seconds + 30} seconds",
                }
                return ExecutionResult(
                    output_blocks=[TextContent(data=json.dumps(result, indent=2))],
                )

            except Exception as recording_error:
                result = {
                    "success": False,
                    "operation": "run_massgen_with_recording",
                    "error": f"Recording failed: {str(recording_error)}",
                }
                return ExecutionResult(
                    output_blocks=[TextContent(data=json.dumps(result, indent=2))],
                )

    except Exception as e:
        result = {
            "success": False,
            "operation": "run_massgen_with_recording",
            "error": f"Failed to run MassGen with recording: {str(e)}",
        }
        return ExecutionResult(
            output_blocks=[TextContent(data=json.dumps(result, indent=2))],
        )
